# Site settings
title: 坚瓠
SEOTitle: 坚瓠 | D Blog
header-img: img/home-bg.jpg
email: jaded3055@gmail.com
description: "死去的山，绿是一场惯性"
keyword: "坚瓠，JadeD, 博客，个人主页，订阅号"
url: "http://jaded.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# Publish posts or collection documents with a future date.
future: true


# SNS settings
RSS: false
instagram_username:  jadededaj
github_username:  JadeDon



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: [
           "less",
           "node_modules",
           "Gruntfile.js",
           "package.json",
           "README.md"
        ]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Featured Tags
featured-tags: true  
featured-condition-size: 1     # A tag will be featured if the size of it is more than this condition value



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Netease settings
netease_comment: false



# Analytics settings
# Google Analytics
ga_track_id: 'UA-250118705-1'            # Format: UA-xxxxxx-xx
ga_domain: jaded.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Dissenter, Diaspora, Delightful"
sidebar-avatar: /img/avatar-d.png      # use absolute URL, seeing it's used in both `/` and `/about/`



<!-- gitment start -->
<div id="container"></div>
<link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">
<script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script>
<script>
var gitment = new Gitment({
  id: 'location.href', // 可选。默认为 location.href
  owner: 'JadeDon',
  repo: 'jaded.github.io',
  oauth: {
    client_id: '610983c5eec985987060',
    client_secret: '76d61d157f866b0fabcd2126a0d634629afe883c',
  },
})
gitment.render('container')
</script>



const myTheme = {
    render(state, instance) {
      const container = document.createElement('div')
      container.lang = "en-US"
      container.className = 'gitment-container gitment-root-container'
      container.appendChild(instance.renderHeader(state, instance))
      container.appendChild(instance.renderEditor(state, instance))
      container.appendChild(instance.renderComments(state, instance))
      container.appendChild(instance.renderFooter(state, instance))
      return container
    },
  }
  const gitment = new Gitment({
    // ...
    theme: myTheme,
  })
  gitment.render('container')




# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: 
[
    {title: "酸砂软糖", href: "https://soursand.wordpress.com/"},
    {title: "tikabeta", href: "https://tikabeta.neocities.org/"},
    {title: "中国数字时代", href: "https://chinadigitaltimes.net/chinese/"},
    {title: "书格", href: "https://new.shuge.org"}
]
